# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

parameters:
  - name: releaseVersion
    displayName: Release Version
    type: string
    # If releaseVersion == latest then the version is extracted from release.version file in root directory of the repo
    default: "latest"

jobs:
  - template: 'templates/jobs/system-tests/acceptance_helm_jobs.yaml'


