# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

parameters:
  - name: releaseVersion
    displayName: Release Version
    type: string
    # If releaseVersion == latest then the version is extracted from release.version file in root directory of the repo
    default: "latest"

# Regression tests are split into 6 jobs because of timeout set to 360 minutes for each job
jobs:
  - template: 'templates/jobs/system-tests/regression_jobs.yaml'
    # This is needed to propagate releaseVersion parameter down to system_test_general.yaml
    parameters:
      releaseVersion: '${{ parameters.releaseVersion }}'
